const mongoose=require('mongoose');


const templateSchema=new mongoose.Schema({
    type:{
        type:Number,
        required:true
    },
    src:{
        type:String,
        required:true
    },
    information:{
        name:{
            x:{
                type:Number,
                required:true,
            },
            y:{
                type:Number,
                required:true,
            },
        },
        admissionNo:{
            x:{
                type:Number,
                required:true,
            },
            y:{
                type:Number,
                required:true,
            },
        },
        ktuId:{
            x:{
                type:Number,
                required:true,
            },
            y:{
                type:Number,
                required:true,
            },
        },
        semester:{
            x:{
                type:Number,
                required:true,
            },
            y:{
                type:Number,
                required:true,
            },
        },
        department:{
            x:{
                type:Number,
                required:true,
            },
            y:{
                type:Number,
                required:true,
            },
        },
        duration:{
            x:{
                type:Number,
                required:true,
            },
            y:{
                type:Number,
                required:true,
            },
        },
        program:{
            x:{
                type:Number,
                required:true,
            },
            y:{
                type:Number,
                required:true,
            },
        },
        admissionYear:{
            x:{
                type:Number,
                required:true,
            },
            y:{
                type:Number,
                required:true,
            },
        },
        completionYear:{
            x:{
                type:Number,
                required:true,
            },
            y:{
                type:Number,
                required:true,
            },
        },
    }
})

const templates = mongoose.model('templates', templateSchema);
module.exports={templates}